/**
 * Progress Summary POML Template
 *
 * Shows beautiful progress visualization anytime.
 * Provides comprehensive project progress reports with visual progress bars,
 * phase breakdowns, velocity metrics, and motivational content.
 */

export const PROGRESS_SUMMARY_POML = `<poml>
  <role>
    You are the Progress Reporting Analyst for {{projectName}}.
  </role>

  <task>
    Generate a comprehensive progress summary showing:
    - Overall project completion
    - Phase-by-phase breakdown with visual progress bars
    - Upcoming milestones
    - Velocity metrics
  </task>

  <context>
    <document src="../planning/TASKS.md" priority="high" />
    <document src="../.claude/state/session-progress.json" priority="critical" />
    <document src="../.claude/state/completed-tasks.json" priority="high" />
    <document src="../.claude/state/checkpoint-history.json" priority="medium" />
  </context>

  <output format="progress-dashboard">
    # 📊 {{projectName}} - PROGRESS REPORT

    **Date:** {{currentDate}}
    **Project Start:** {{projectStartDate}}
    **Days Elapsed:** {{daysElapsed}}

    ## 🎯 OVERALL PROGRESS
    \`\`\`
    {{progressBar}} {{completionPercentage}}%
    \`\`\`

    - **Total Tasks:** {{totalTasks}}
    - **Completed:** {{completedTasks}}
    - **Remaining:** {{remainingTasks}}
    - **Estimated Completion:** {{estimatedCompletionDate}}

    ## 📋 PHASE BREAKDOWN

    {{phaseBreakdown}}

    ## 🎯 UPCOMING MILESTONES

    {{upcomingMilestones}}

    ## 📈 VELOCITY METRICS
    - **Average tasks/day:** {{averageTasksPerDay}}
    - **Last 7 days:** {{tasksLastWeek}} tasks
    - **Checkpoint frequency:** Every {{checkpointFrequency}} tasks
    - **Last checkpoint:** Task #{{lastCheckpoint}} ({{daysSinceLastCheckpoint}} days ago)

    ## 🏆 RECENT ACHIEVEMENTS

    {{recentAchievements}}

    ## 🎉 MOTIVATION
    {{motivationalMessage}}

    ---
    *Progress report generated by DevForge*
  </output>

  <style verbosity="detailed" tone="motivational" language="{{language}}" />
</poml>`;

/**
 * Context for rendering the progress summary POML
 */
export interface ProgressSummaryPOMLContext {
  projectName: string;
  currentDate: string;
  projectStartDate: string;
  daysElapsed: number;
  progressBar: string;
  completionPercentage: number;
  totalTasks: number;
  completedTasks: number;
  remainingTasks: number;
  estimatedCompletionDate: string;
  phaseBreakdown: string;
  upcomingMilestones: string;
  averageTasksPerDay: number;
  tasksLastWeek: number;
  checkpointFrequency: number;
  lastCheckpoint: number;
  daysSinceLastCheckpoint: number;
  recentAchievements: string;
  motivationalMessage: string;
  language: string;
}

/**
 * Render the progress summary POML template
 */
export function renderProgressSummaryPOML(
  context: Partial<ProgressSummaryPOMLContext>
): string {
  let rendered = PROGRESS_SUMMARY_POML;

  // Set defaults
  const defaults: Partial<ProgressSummaryPOMLContext> = {
    currentDate: new Date().toISOString().split('T')[0],
    language: 'English',
    checkpointFrequency: 20,
    motivationalMessage: "Great progress! Keep up the excellent work! 🚀",
    recentAchievements: '    No achievements recorded yet.',
  };

  const mergedContext = { ...defaults, ...context };

  // Replace all placeholders
  Object.entries(mergedContext).forEach(([key, value]) => {
    const placeholder = `{{${key}}}`;
    rendered = rendered.replace(new RegExp(placeholder, 'g'), String(value ?? ''));
  });

  return rendered;
}

/**
 * Phase progress information
 */
export interface PhaseProgress {
  id: string;
  name: string;
  totalTasks: number;
  completedTasks: number;
  percentage: number;
  tasks: TaskInfo[];
  status: 'not-started' | 'in-progress' | 'completed';
}

/**
 * Task information
 */
export interface TaskInfo {
  id: string;
  title: string;
  completed: boolean;
  priority?: 'low' | 'medium' | 'high' | 'critical';
  assignedPhase?: string;
}

/**
 * Milestone information
 */
export interface Milestone {
  name: string;
  description: string;
  estimatedDate: string;
  tasksRequired: number;
  tasksCompleted: number;
  priority: 'low' | 'medium' | 'high';
}

/**
 * Achievement information
 */
export interface Achievement {
  date: string;
  description: string;
  type: 'milestone' | 'quality' | 'velocity' | 'checkpoint';
}

/**
 * Generate visual progress bar
 */
export function generateProgressBar(percentage: number, width: number = 40): string {
  const completed = Math.round((percentage / 100) * width);
  const remaining = width - completed;
  const bar = '█'.repeat(completed) + '░'.repeat(remaining);
  return bar;
}

/**
 * Format phase breakdown section
 */
export function formatPhaseBreakdown(phases: PhaseProgress[]): string {
  return phases
    .map((phase, index) => {
      const progressBar = generateProgressBar(phase.percentage, 30);
      const statusEmoji = phase.status === 'completed' ? '✅' :
                         phase.status === 'in-progress' ? '🔄' : '⬜';

      let output = `    ### ${statusEmoji} Phase ${index + 1}: ${phase.name}\n`;
      output += `    \`\`\`\n`;
      output += `    ${progressBar}  ${phase.percentage}%\n`;
      output += `    \`\`\`\n`;
      output += `    **Tasks:** ${phase.completedTasks}/${phase.totalTasks}\n\n`;

      // Add task list
      phase.tasks.forEach(task => {
        const checkmark = task.completed ? '✅' : '⬜';
        const priority = task.priority ? ` [${task.priority.toUpperCase()}]` : '';
        output += `    - ${checkmark} ${task.id}: ${task.title}${priority}\n`;
      });

      return output;
    })
    .join('\n\n');
}

/**
 * Format upcoming milestones section
 */
export function formatUpcomingMilestones(milestones: Milestone[]): string {
  if (milestones.length === 0) {
    return '    No upcoming milestones defined.';
  }

  return milestones
    .map((milestone, index) => {
      const progress = milestone.tasksRequired > 0
        ? Math.round((milestone.tasksCompleted / milestone.tasksRequired) * 100)
        : 0;
      const progressBar = generateProgressBar(progress, 20);

      let output = `    ${index + 1}. **${milestone.name}** - ${milestone.estimatedDate}\n`;
      output += `       ${milestone.description}\n`;
      output += `       Progress: ${progressBar} ${progress}% (${milestone.tasksCompleted}/${milestone.tasksRequired} tasks)\n`;

      return output;
    })
    .join('\n');
}

/**
 * Format recent achievements section
 */
export function formatRecentAchievements(achievements: Achievement[]): string {
  if (achievements.length === 0) {
    return '    No achievements recorded yet. Keep working to unlock achievements!';
  }

  const typeEmojis: Record<Achievement['type'], string> = {
    milestone: '🎯',
    quality: '🏆',
    velocity: '⚡',
    checkpoint: '✅',
  };

  return achievements
    .slice(0, 10) // Show last 10 achievements
    .map(achievement => {
      const emoji = typeEmojis[achievement.type];
      return `    ${emoji} ${achievement.date}: ${achievement.description}`;
    })
    .join('\n');
}

/**
 * Calculate estimated completion date
 */
export function calculateEstimatedCompletion(
  remainingTasks: number,
  averageTasksPerDay: number,
  startDate: Date = new Date()
): string {
  if (averageTasksPerDay === 0) {
    return 'Unable to estimate (no velocity data)';
  }

  const daysRemaining = Math.ceil(remainingTasks / averageTasksPerDay);
  const completionDate = new Date(startDate);
  completionDate.setDate(completionDate.getDate() + daysRemaining);

  return completionDate.toISOString().split('T')[0];
}

/**
 * Generate motivational message based on progress
 */
export function generateMotivationalMessage(
  completionPercentage: number,
  averageTasksPerDay: number,
  daysElapsed: number
): string {
  const messages: Record<string, string[]> = {
    early: [
      "🚀 Great start! You're building solid momentum!",
      "🌟 Excellent beginning! Keep this energy going!",
      "💪 Strong start! The foundation is being laid perfectly!",
    ],
    quarter: [
      "🎯 25% complete! You're making real progress!",
      "⭐ Quarter of the way there! Fantastic work!",
      "🔥 Heating up! 25% done and going strong!",
    ],
    half: [
      "🎉 Halfway there! Outstanding progress!",
      "🏆 50% complete! You're crushing it!",
      "💎 Midway milestone achieved! Incredible work!",
    ],
    threeQuarter: [
      "🚀 75% complete! The finish line is in sight!",
      "⭐ Three quarters done! Almost there!",
      "🔥 Nearly complete! Keep pushing forward!",
    ],
    final: [
      "🎊 90%+ complete! Sprint to the finish!",
      "🏁 Final stretch! You've got this!",
      "💪 Almost done! Give it your all!",
    ],
    completed: [
      "🎉🎉🎉 PROJECT COMPLETE! Congratulations! 🎉🎉🎉",
      "🏆 FINISHED! Outstanding achievement!",
      "⭐ SUCCESS! You did it! Celebrate this victory!",
    ],
  };

  let category: keyof typeof messages;
  if (completionPercentage >= 100) category = 'completed';
  else if (completionPercentage >= 90) category = 'final';
  else if (completionPercentage >= 75) category = 'threeQuarter';
  else if (completionPercentage >= 50) category = 'half';
  else if (completionPercentage >= 25) category = 'quarter';
  else category = 'early';

  const messageList = messages[category];
  const randomMessage = messageList[Math.floor(Math.random() * messageList.length)];

  // Add velocity praise if doing well
  if (averageTasksPerDay >= 5) {
    return `${randomMessage}\n\n    ⚡ Velocity: ${averageTasksPerDay.toFixed(1)} tasks/day - You're on fire!`;
  } else if (averageTasksPerDay >= 3) {
    return `${randomMessage}\n\n    📈 Velocity: ${averageTasksPerDay.toFixed(1)} tasks/day - Great pace!`;
  }

  return randomMessage;
}

/**
 * Progress Summary Manager
 *
 * Manages progress tracking and report generation
 */
export class ProgressSummaryManager {
  private projectStartDate: Date;
  private completedTasks: TaskInfo[] = [];
  private phases: PhaseProgress[] = [];
  private milestones: Milestone[] = [];
  private achievements: Achievement[] = [];

  constructor(projectStartDate: Date = new Date()) {
    this.projectStartDate = projectStartDate;
  }

  /**
   * Set project phases
   */
  setPhases(phases: PhaseProgress[]) {
    this.phases = phases;
  }

  /**
   * Set milestones
   */
  setMilestones(milestones: Milestone[]) {
    this.milestones = milestones;
  }

  /**
   * Add completed task
   */
  addCompletedTask(task: TaskInfo) {
    this.completedTasks.push({ ...task, completed: true });
  }

  /**
   * Add achievement
   */
  addAchievement(achievement: Achievement) {
    this.achievements.push(achievement);
  }

  /**
   * Calculate velocity (tasks per day)
   */
  calculateVelocity(): number {
    const daysElapsed = Math.max(
      1,
      Math.ceil((Date.now() - this.projectStartDate.getTime()) / (1000 * 60 * 60 * 24))
    );
    return this.completedTasks.length / daysElapsed;
  }

  /**
   * Get tasks completed in last N days
   */
  getTasksInLastDays(days: number): number {
    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - days);

    // In real implementation, would filter by task completion date
    // For now, estimate based on velocity
    const velocity = this.calculateVelocity();
    return Math.round(velocity * days);
  }

  /**
   * Generate complete progress summary
   */
  generateSummary(totalTasks: number): Partial<ProgressSummaryPOMLContext> {
    const completedCount = this.completedTasks.length;
    const remainingTasks = totalTasks - completedCount;
    const completionPercentage = Math.round((completedCount / totalTasks) * 100);
    const daysElapsed = Math.ceil(
      (Date.now() - this.projectStartDate.getTime()) / (1000 * 60 * 60 * 24)
    );
    const averageTasksPerDay = this.calculateVelocity();
    const tasksLastWeek = this.getTasksInLastDays(7);

    return {
      projectStartDate: this.projectStartDate.toISOString().split('T')[0],
      daysElapsed,
      progressBar: generateProgressBar(completionPercentage, 40),
      completionPercentage,
      totalTasks,
      completedTasks: completedCount,
      remainingTasks,
      estimatedCompletionDate: calculateEstimatedCompletion(
        remainingTasks,
        averageTasksPerDay
      ),
      phaseBreakdown: formatPhaseBreakdown(this.phases),
      upcomingMilestones: formatUpcomingMilestones(this.milestones),
      averageTasksPerDay: Math.round(averageTasksPerDay * 10) / 10,
      tasksLastWeek,
      recentAchievements: formatRecentAchievements(this.achievements),
      motivationalMessage: generateMotivationalMessage(
        completionPercentage,
        averageTasksPerDay,
        daysElapsed
      ),
    };
  }

  /**
   * Get summary statistics
   */
  getStatistics() {
    const totalTasks = this.phases.reduce((sum, phase) => sum + phase.totalTasks, 0);
    const completedCount = this.completedTasks.length;
    const velocity = this.calculateVelocity();

    return {
      totalTasks,
      completedTasks: completedCount,
      remainingTasks: totalTasks - completedCount,
      completionPercentage: totalTasks > 0 ? Math.round((completedCount / totalTasks) * 100) : 0,
      velocity,
      totalPhases: this.phases.length,
      completedPhases: this.phases.filter(p => p.status === 'completed').length,
      totalMilestones: this.milestones.length,
      achievements: this.achievements.length,
    };
  }
}

/**
 * Create default phases for a project
 */
export function createDefaultPhases(projectType: string): PhaseProgress[] {
  const basePhases: PhaseProgress[] = [
    {
      id: 'setup',
      name: 'Project Setup',
      totalTasks: 5,
      completedTasks: 0,
      percentage: 0,
      tasks: [],
      status: 'not-started',
    },
    {
      id: 'development',
      name: 'Core Development',
      totalTasks: 30,
      completedTasks: 0,
      percentage: 0,
      tasks: [],
      status: 'not-started',
    },
    {
      id: 'testing',
      name: 'Testing & QA',
      totalTasks: 10,
      completedTasks: 0,
      percentage: 0,
      tasks: [],
      status: 'not-started',
    },
    {
      id: 'deployment',
      name: 'Deployment & Launch',
      totalTasks: 5,
      completedTasks: 0,
      percentage: 0,
      tasks: [],
      status: 'not-started',
    },
  ];

  // Add type-specific phases
  const typeSpecificPhases: Record<string, PhaseProgress[]> = {
    web: [
      {
        id: 'ui-design',
        name: 'UI/UX Design',
        totalTasks: 8,
        completedTasks: 0,
        percentage: 0,
        tasks: [],
        status: 'not-started',
      },
    ],
    api: [
      {
        id: 'database-design',
        name: 'Database Design',
        totalTasks: 7,
        completedTasks: 0,
        percentage: 0,
        tasks: [],
        status: 'not-started',
      },
    ],
    mobile: [
      {
        id: 'platform-setup',
        name: 'Platform Setup (iOS/Android)',
        totalTasks: 10,
        completedTasks: 0,
        percentage: 0,
        tasks: [],
        status: 'not-started',
      },
    ],
  };

  const additionalPhases = typeSpecificPhases[projectType] || [];
  return [...basePhases.slice(0, 1), ...additionalPhases, ...basePhases.slice(1)];
}

/**
 * Create default milestones for a project
 */
export function createDefaultMilestones(projectType: string, totalTasks: number): Milestone[] {
  const today = new Date();
  const addDays = (days: number) => {
    const date = new Date(today);
    date.setDate(date.getDate() + days);
    return date.toISOString().split('T')[0];
  };

  return [
    {
      name: 'Project Foundation',
      description: 'Basic setup and architecture complete',
      estimatedDate: addDays(7),
      tasksRequired: Math.ceil(totalTasks * 0.1),
      tasksCompleted: 0,
      priority: 'high',
    },
    {
      name: 'Core Features MVP',
      description: 'Minimum viable product with core features',
      estimatedDate: addDays(30),
      tasksRequired: Math.ceil(totalTasks * 0.5),
      tasksCompleted: 0,
      priority: 'high',
    },
    {
      name: 'Feature Complete',
      description: 'All planned features implemented',
      estimatedDate: addDays(60),
      tasksRequired: Math.ceil(totalTasks * 0.8),
      tasksCompleted: 0,
      priority: 'medium',
    },
    {
      name: 'Production Ready',
      description: 'Tested, documented, and ready for launch',
      estimatedDate: addDays(90),
      tasksRequired: totalTasks,
      tasksCompleted: 0,
      priority: 'high',
    },
  ];
}
