/**
 * Auto-Refresh Continuation Template
 *
 * CRITICAL: This template generates continuation prompts to prevent context loss
 */

export const REFRESH_CONTINUATION_TEMPLATE = `# 🔄 DevForge Auto-Refresh Continuation

**Project:** {{projectName}}
**Saved:** {{timestamp}}
**Session:** {{sessionId}}

---

## ⚡ Quick Resume

This is an auto-refresh continuation point. The complete project state has been saved.
You can seamlessly continue development from exactly where you left off.

### Current Context

- **Project Type:** {{projectType}}
- **Tech Stack:** {{techStack}}
- **Current Phase:** {{currentPhase}}
- **Progress:** {{completedTasks}}/{{totalTasks}} tasks ({{progressPercentage}}%)
- **Status:** {{status}}

---

## 📋 What You Were Working On

### Last Active Phase
{{currentPhase}}

### Recently Completed
{{recentlyCompleted}}

### Next Immediate Tasks
{{nextImmediateTasks}}

---

## 🎯 Project Overview

### Features Being Implemented
{{featuresList}}

### Architecture
- **Pattern:** {{architecturePattern}}
- **Structure:** {{projectStructure}}

### Tech Stack Details
{{techStackDetails}}

---

## 📍 Current State

### Files Created
{{filesCreated}}

### In Progress
{{inProgressItems}}

### Pending
{{pendingItems}}

---

## 🔍 Context Documents

All project context is preserved in:

1. **PROJECT.poml** - Complete project manifest
2. **.devforge/state.json** - Detailed state snapshot
3. **constitution.md** - Immutable principles
4. **SPEC.md** - Project specification
5. **PLAN.md** - Implementation plan
6. **TASKS.md** - Task breakdown
7. **PROGRESS.md** - Current progress

---

## 💡 How to Continue

### Option 1: Resume Current Task
Continue with the current phase: **{{currentPhase}}**

Next steps:
{{nextSteps}}

### Option 2: Check Status
Use the \`get_project_status\` tool to see complete current state.

### Option 3: Add Features
Use the \`add_feature\` tool to add new functionality.

### Option 4: Generate Updated POML
Use the \`generate_poml\` tool to update the project manifest.

---

## 📊 Progress Breakdown

### Completed Tasks ({{completedTasks}})
{{completedTasksList}}

### Remaining Tasks ({{remainingTasks}})
{{remainingTasksList}}

### Estimated Time to Completion
{{estimatedTime}}

---

## 🎨 Project-Specific Context

### {{projectType}} Specific Details
{{projectSpecificContext}}

### Key Decisions Made
{{keyDecisions}}

### Technical Constraints
{{technicalConstraints}}

---

## 🚀 Quick Commands

To continue immediately:

\`\`\`
# Check current status
get_project_status("{{projectName}}")

# Add a new feature
add_feature("{{projectName}}", "feature-name")

# Save state again (before context limit)
auto_refresh("{{projectName}}")

# Update POML manifest
generate_poml("{{projectName}}")
\`\`\`

---

## 🔒 State Integrity

- ✅ State saved successfully
- ✅ POML manifest updated
- ✅ All context preserved
- ✅ No data loss
- ✅ Ready to resume

**State File:** .devforge/state.json
**POML File:** PROJECT.poml
**Integrity Hash:** {{stateHash}}

---

## ⚠️ Important Notes

1. **Context Fully Preserved**: All project context has been saved
2. **No Repetition Needed**: Don't restart from scratch
3. **Incremental Progress**: Continue from exactly where you stopped
4. **Auto-Refresh Again**: Use auto_refresh before next context limit
5. **POML is Truth**: PROJECT.poml is the single source of truth

---

## 🎯 Recommended Next Action

{{recommendedAction}}

---

**Auto-Refresh System Status:** ✅ Active
**Context Loss Prevention:** ✅ Enabled
**State Synchronization:** ✅ Complete

*Generated by DevForge Auto-Refresh System*
*Session ID: {{sessionId}}*
*Timestamp: {{timestamp}}*
`;

export interface RefreshContinuationContext {
  projectName: string;
  timestamp: string;
  sessionId: string;
  projectType: string;
  techStack: string;
  currentPhase: string;
  completedTasks: number;
  totalTasks: number;
  progressPercentage: number;
  status: string;
  recentlyCompleted: string;
  nextImmediateTasks: string;
  featuresList: string;
  architecturePattern: string;
  projectStructure: string;
  techStackDetails: string;
  filesCreated: string;
  inProgressItems: string;
  pendingItems: string;
  nextSteps: string;
  completedTasksList: string;
  remainingTasks: number;
  remainingTasksList: string;
  estimatedTime: string;
  projectSpecificContext: string;
  keyDecisions: string;
  technicalConstraints: string;
  stateHash: string;
  recommendedAction: string;
}

export function renderRefreshContinuation(context: Partial<RefreshContinuationContext>): string {
  let rendered = REFRESH_CONTINUATION_TEMPLATE;

  const defaults: Partial<RefreshContinuationContext> = {
    timestamp: new Date().toISOString(),
    sessionId: generateSessionId(),
    recentlyCompleted: 'See PROGRESS.md for details',
    nextImmediateTasks: 'See TASKS.md for breakdown',
    projectSpecificContext: 'No specific context notes',
    keyDecisions: 'See PLAN.md for decisions',
    technicalConstraints: 'See SPEC.md for constraints',
    stateHash: generateStateHash(),
    recommendedAction: 'Continue with current phase tasks',
  };

  const mergedContext = { ...defaults, ...context };

  Object.entries(mergedContext).forEach(([key, value]) => {
    const placeholder = `{{${key}}}`;
    rendered = rendered.replace(new RegExp(placeholder, 'g'), String(value ?? ''));
  });

  return rendered;
}

function generateSessionId(): string {
  return `devforge-${Date.now()}-${Math.random().toString(36).substring(7)}`;
}

function generateStateHash(): string {
  const timestamp = Date.now().toString();
  return Buffer.from(timestamp).toString('base64').substring(0, 16);
}
